name="Libmacgpg"
appName="Libmacgpg.framework"

pkgProj_corename=(Libmacgpg_Core.pkgproj LibmacgpgXPC_Core.pkgproj)
pkgCoreName=(Libmacgpg_Core.pkg LibmacgpgXPC_Core.pkg)
infoPlist=Resources/Info.plist


unset REVISION PRERELEASE
MAJOR=0
MINOR=4
#REVISION=0
#PRERELEASE=0

source "$(dirname "${BASH_SOURCE[0]}")/Dependencies/GPGTools_Core/newBuildSystem/versioning.sh"
