name="Libmacgpg"
appName="Libmacgpg.framework"

pkgProj_dir="Installer"
pkgProj_corename=(Libmacgpg_core.pkgproj LibmacgpgXPC_core.pkgproj)
pkgProj_name="Libmacgpg.pkgproj"
pkgName="Libmacgpg.pkg"



unset REVISION PRERELEASE


MAJOR=0
MINOR=3
#REVISION=0
#PRERELEASE=0




# Versioning

# isMasterBranch: Selbsterklärend (true/false)
# buildNumber: Stunden seit dem Jahr 2000 (113316)
# repoDirtyState: "+" wenn uncommited changes vorhanden sind (+/)
# commitHash: Hash des commits, eventuell dirtyState (7b24eed/7b24eed+)
# versionType: Typ der Version (/b/n)


[[ "$(git symbolic-ref -q HEAD)" == "refs/heads/master" ]] && isMasterBranch=true || isMasterBranch=false


buildNumber=$(($(date +"%s") / 3600 - 262968))
repoDirtyState=$(test -z "$(git status --porcelain)" || echo "+")
commitHash=$(git rev-parse --short HEAD)$repoDirtyState

REVISION=${REVISION:+.$REVISION}

if $isMasterBranch ;then
	unset COMMIT
	versionType=${PRERELEASE:0:1}
else
	COMMIT=" ($commitHash)"
	versionType="n"
fi


version=${MAJOR}.${MINOR}${REVISION}${PRERELEASE}${COMMIT}
build_version=${buildNumber}${versionType}

