MAJOR=0
MINOR=5
#REVISION=0
#PRERELEASE=0

COMMIT_HASH=$(git rev-parse --short HEAD)$(test -z "$(git status --porcelain)" || echo "+")
VERSION="${MAJOR}.${MINOR}${REVISION:+.$REVISION}${PRERELEASE} ($COMMIT_HASH)"
BUILD_VERSION=0n
